### ISSUE TITLE
hide_submit.php

### ISSUE THREAD

**Issue by j4jes** [123andy/redcap-hook-framework#12]
Hi Andy,

I tried using the hide_submit.php hook in my instrument, and it seems to work. I was hoping to use it conditionally, similar to PHS's hide_submit_button.php which uses an action tag that can go in the last field of a survey. This way the submit button will appear once the last field is answered. Unfortunately the hide_submit_button hook gives me an error for some reason:

PHP Fatal error:  Call to undefined function init_tags() in /var/www/html/redcap/hooks/framework/resources/hide_submit_button.php on line 21

Is there any way your hide_submit.php hook can be used conditionally with branching logic? 

Thanks!

**Comment by 123andy** [comment]
This functionality is now present in the survey ui tweaks external module through the REDCap Repo.
