### ISSUE TITLE
Adding new REDCap functions?

### ISSUE THREAD

**Issue by botsmack** [123andy/redcap-hook-framework#14]
REDCap recently released (with version 9.5.0) two new hook functions: `redcap_pdf` and `redcap_email`. Using this framework caused the configuration check to display warnings. When this happens are we supposed to add these new functions to your file and mirror the template from the other functions?

From REDCap's `hooks_functions.php` file:

```
// REDCAP_PDF
function redcap_pdf($project_id, $metadata, $data, $instrument=null, $record=null, $event_id=null, $instance=1)
{
    // Set the full path of the project handler PHP script located inside the
    // project-specific sub-folder, which itself exists in the main Hooks folder.
    $project_handler_script = dirname(__FILE__) . "/hooks/pid{$project_id}/".__FUNCTION__.".php";
    // Check if the project handler PHP script exists for this project, and if so,
    // then "include" the script to execute it. If not, do nothing.
    if (file_exists($project_handler_script)) include $project_handler_script;
    // Return metadata and data in an associative array after being manipulated. 
    // If not changed, then no need to return anything.
    return array('metadata'=>$metadata, 'data'=>$data);
}

// REDCAP_EMAIL
function redcap_email($to, $from, $subject, $message, $cc, $bcc, $fromName, $attachments)
{
    // You may want to send out emails via an alternative method or configuration,
    // OR maybe change something in a particular email based on some decision logic.

    // If this hook function returns FALSE or 0, that will prevent REDCap's email function from sending the email using the normal method.
    // If anything other than FALSE or 0 is returned (including not returning anything), REDCap will proceed with sending the email as usual.
    return TRUE;
}
```

In order to make these compliant with the framework structure you've developed, do we just need to add them like so?

```
// redcap_pdf
function redcap_pdf($project_id, $metadata, $data, $instrument=null, $record=null, $event_id=null, $instance=1)
{
    $hook_event = __FUNCTION__;
    foreach (get_hook_include_files($hook_event, $project_id) as $script) include $script;
}


// redcap_email
function redcap_email($to, $from, $subject, $message, $cc, $bcc, $fromName, $attachments)
{
    $hook_event = __FUNCTION__;
    foreach (get_hook_include_files($hook_event, $project_id) as $script) include $script;
}
```

**Comment by 123andy** [comment]
Yes you could if you are still using the framework.  We have mostly migrated to EMs for all of that code, but so long as you don't have any hooks that utilize those methods it shouldn't cause any harm to have them missing from the main file...

-andy

**Comment by kirenotneb** [comment]
@123andy are there any guides that you're aware of for migrating from Hooks/Plugins to External Modules?

**Comment by 123andy** [comment]
We've been on a steady path of pushing things over...  nothing that comes to mind.  Obviously you don't need redcap_connect.  I think the point of most confusion is dealing with URLs and the concept of a plugin page..

-A



Andrew Martin, PhD
Biomedical Data Management Solutions Lead

Research IT - Technology and Digital Solutions
Stanford Medicine

650 380 3405 (cell)
455 Broadway, Redwood City, CA 94063
https://tds.stanfordmedicine.org/

________________________________
